# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pu_I5xUUoy4avNwuf2R_f43gUsmOC6mh
"""

def kasallik_tashqisi(belgi):
 if belgi == "Istima":
   return "Parasitamol iching"
 elif belgi =="Bosh og'rig'i":
   return "Bolnol"
 elif belgi =="Quloq og'rig'i":
   return "Ibuprofen ichin"
 elif belgi =="Tomoq og'rig'i":
   return "Anzibel ichin"
 elif belgi =="Qorin og'rig'i":
   return "Lineks ichin"
 elif belgi =="koz og'rig'i":
   return "Fraselinda  yuvin"
 elif belgi ==" Oshqozon og'rig'i":
   return "Ibuklin ichin"
 elif belgi =="Tish og'rig'i":
  return "Senepar"
 elif belgi =="Bog'um og'rig'i":
   return " cadelta "
 elif belgi ==" Bel og'rig'i":
   return "Kyupen ichin"

 else:
   return"Shifokorga murojot qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashqisi(belgi)
print(natija)

def sport_turlari(belgi):
 if belgi == "fudbool":
   return "Futbolning asosiy qoidalari shundan iborat:O'yinchilar to'pni oyoqlari bilan boshqaradi, qo'llari bilan faqat darvozabonlar o'ynashi mumkin.To'pni raqib darvozasiga kiritish maqsad.O'yin maydoni to'g'ri shakldagi to'rtburchak, uning uzunligi 100-110 metr, kengligi esa 64-75 metr atrofida bo'ladi."
 elif belgi =="Baskedbol":
   return "Basketbolning asosiy maqsadi:Raqibning savatchasiga to‘pni kiritish va ko‘proq ochko to‘plash.To‘pni ushlab, raqibga imkoniyat bermaslik."
 elif belgi =="Gandbol":
   return "O‘yin davomiyligi: Gandebol o‘yinlari odatda 60 daqiqa davom etadi, ikki bo‘limga bo‘linadi (har biri 30 daqiqa). Agar o‘yin tugagandan keyin hisob teng bo‘lsa, ba'zi musobaqalarda qo‘shimcha vaqt yoki penalti seriyasi o‘tkazilishi mumkin.To‘pni boshqarish: O'yinchilar to‘pni faqat qo'llari bilan boshqarishlari mumkin. To‘pni dribling (yurish) yoki passlar orqali jamoa o'rtasida uzatish mumkin.Darvoza va ochko: To‘pni raqib jamoaning darvozasiga kiritish orqali ochko olish mumkin. O‘yinchilarga darvoza maydonchasi ichida maxsus cheklovlar mavjud, masalan, faqat darvozabon to‘pni qo‘l bilan ushlashi mumkin."
 elif belgi =="Shahmat":
   return " bu ikki kishilik strategik doshbo‘z o'yini bo'lib, unda har bir o'yinchi 16 ta shaxmat to'pi bilan o'ynaydi: 1 ta shoh, 1 ta vazir, 2 ta fillar, 2 ta ot, 2 ta qal'a va 8 ta piyoda. O'yinning maqsadi — raqibning shohini shahmat holatiga keltirib, uni mat qilish, ya'ni shohni qochish imkoniyatiga ega bo'lmaydigan holatga keltirishdir."
 elif belgi =="Erkin suzish":
   return "Erkin kurashda raqibni yengishning asosiy maqsadi — uni to‘liq yerga yiqitish yoki uning holatini shunday qilib o‘zgartirishki, raqib kurashni davom ettirishni imkonsiz deb hisoblasin."
 elif belgi =="Hakkey":
   return "bu ikkita jamoa o‘rtasida o‘ynaladigan jismoniy sport turi bo‘lib, o‘yinda har bir jamoa raqibning darvozasiga to‘p kiritishga harakat qiladi. Hokkeyning bir nechta turlari mavjud, lekin eng mashhur va keng tarqalgan shakllari muz hokkeyi va maydon hokkeyidir. Ular o‘ziga xos qoidalar, maydon va uskuna talablariga ega, ammo ikkalasining umumiy maqsadi raqib darvozasiga gol urishdir."
 elif belgi ==" Boks":
   return " bu ikki o'yinchi o'rtasida jangovar sport turi bo'lib, unda maqsad raqibni qochirish yoki zarbalar bilan yengishdir. Boksda o'yinchilar maxsus qo'lqoplar kiyib, bir-biriga zarbalar berib, o'zining raqibini ko'proq zarba berish orqali yengishga harakat qilishadi. O'yin belgilangan vaqt davomida yoki raqibning raqibini nokautga uchratib tugaydi."
 elif belgi =="Kurash":
  return "bu ikki kishilik jangovar sport turi bo'lib, unda o'yinchilar bir-birlarini ushlab yoki zarbalar bilan yengishga harakat qiladilar. Kurashda o'yinchilar raqibni yerga yiqitishga, uning harakatini cheklashga yoki unga yengil texnikalarni qo'llashga intiladilar. Kurashning ko'plab turlari mavjud, ular o'zaro farq qiladigan qoidalar, texnikalar va strategiyalarga ega."
 elif belgi =="Hakkey":
   return "bu ikkita jamoa o'rtasida o'ynaladigan sport turi bo'lib, o'yinda har bir jamoa raqibning darvozasiga to'p kiritishga harakat qiladi. Hokkey turli shakllarda o'ynaladi, lekin eng mashhur va keng tarqalgan shakllari muz hokkeyi va maydon hokkeyidir. Ularning har biri o'ziga xos qoidalar, usullar va uskunalarga ega. "
 elif belgi =="Badmiton":
   return "bu ikki yoki to‘rt nafar o‘yinchi o‘rtasida o‘ynaladigan sport turi bo‘lib, o‘yin davomida o‘yinchilar shuttlecock (yoki birdie) deb ataladigan maxsus to‘pni raqibning maydoniga yo‘llashga harakat qiladilar. Badminton juda tezkor va mahoratni talab qiladigan sport bo‘lib, o‘yinchilar tez-tez tezlik, refleks va strategiyani birlashtirib, turli xil zarbalar bilan raqibni yengishga harakat qilishadi."

 else:
   return"Buni bilmayman"
belgi=input("Qanday sport turga qiziqaz  ")
natija=sport_turlari(belgi)
print(natija)